/* Autogenerated by png2wx.pl on Mon May  4 16:35:57 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images(void);

extern wxBitmap *_img_Polar;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_polar;
extern wxString _svg_polar_rollover;
extern wxString _svg_polar_toggled;
#endif


#endif /* ICONS_H */
